TechDivision:
  NeosVarnishAdaptor:
    cacheHeaders:
      defaultMaximumAge: 60
      defaultSharedMaximumAge: 31536000

    spiderIndexingPathAndFilename: %FLOW_PATH_DATA%Temporary/VarnishSpider.txt
